sudo: required
services:
  - docker
language: generic
before_install:
  - docker build --build-arg AFFECTIVA_SDK_URL=$AFFECTIVA_SDK_URL --build-arg BRANCH=$TRAVIS_BRANCH --tag=v1.0.0:affectiva-auto .
