sudo: required
services:
  - docker
language: generic
before_install:
  - docker build --build-arg API_KEY=$API_KEY --build-arg BRANCH=$TRAVIS_BRANCH --file=docker/Dockerfile --tag=v1.0.0:affectiva-auto .
