sudo: required
services:
  - docker
language: generic
before_install:
  - docker build --build-arg AFFECTIVA_AUTO_SDK_1_1_URL=$AFFECTIVA_AUTO_SDK_1_1_URL --build-arg BRANCH=$TRAVIS_BRANCH --tag=v1.0.0:affectiva-auto .
